apiVersion: v1
data:
    foo: ENC[AES256_GCM,data:NXnj,iv:u+VQro1752w3SHujtsGWQ9lSeJdRMaCdlQC7IPE3N1Y=,tag:9OCX4LVq9vPM4/p0fs17Sw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: database-secret
    namespace: tools
sops:
    age:
        - recipient: age17rl8aj6z7me9rj8vpjesujxpkwrducrhtdv7fvamm592z8280pusfrruup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTmdGZ2hPMnE0bVR0Qm1x
            UEZ4b2lKSDkrVWRKVCs4d3p5Um1NV3VKUmdRCjIrNjVGQ2VMQVMvUVFZSmVvalhB
            aENvTENCNThBYmo3N0x6dEFVNDhOWmsKLS0tIFpmQ1F1UFhPUHJSaHpSUXFGTFdT
            ZHBTOVMzWTMrVGQ1ZTlOUmNtQ3VWSFUKiEbCfFJO8Lde+dkp3nKaQ7kLuZyyevDE
            XeBK/I9WUHhLyOQcTT9rLqXmzj1QFY3PEBR8w2MYOCwitpuevhrz9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-28T02:30:06Z"
    mac: ENC[AES256_GCM,data:nMHY3R2Xrvws8dcDuBc0r79/Id6TgOALx/lPmq+P44DUCzYRtqx1HaRiI2kAl0tL6PRLDFk3HaQ9YRu2smWHibWyabcbvX+jn4JdHXekBRmpOhyFXohavyL3Vg/WNJRSh84Z+vwLX10+XcWNkyDsAmRuu+ECKyd6brx2qxwzAzY=,iv:ZPsCJL6BdpJPtVIdIfKGeGzzt8xyo2uAQluexcGQo5o=,tag:vs6s/UO111y8zTj5rDJOgQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
