apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - ../base/alpine
  - ./tandoor
  - ./cloudflare
patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
      namespace: podinfo
