apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-credentials
type: Opaque
stringData:
    #ENC[AES256_GCM,data:lZxlagQh0yZfKo3gbWqBvymbfp4gJw==,iv:AVqm921R2GC8ENVjYQMRjmk8QuQClpZ2+EMFxE9h+AY=,tag:7qSULk126nXhGkhSAPLEUw==,type:comment]
    account: ENC[AES256_GCM,data:hN8cgGsoxGLep5o+5MlGSKLNaEKxBgGD+B7oaJXTOt8=,iv:ZRgqPIVS4l7YqMwhW5zPHZw8p8F0l7/Hmb9+J87KLGA=,tag:/8OD9VJmrXntJHAEdcYqZA==,type:str]
    #ENC[AES256_GCM,data:LMfCIm/cQP+eoYFw,iv:DhlBjLKSr/M0Mx/TYf2bdcWgwLc/TynGVesCMVt/aEo=,tag:8zGHIUIUXynpqyElW8owDA==,type:comment]
    tunnelName: ENC[AES256_GCM,data:tx8mHbEl1A==,iv:3K4KyWezEwIYHegIXJ5jQuuKh5KVqFgXNEYPRjmCKJU=,tag:hujr8XyGd79mq16sgQyjXA==,type:str]
    #ENC[AES256_GCM,data:0bJapvkZw0EGK96US9UDyR0=,iv:nvfD340Nr8DREi86ovPGD6zQ/raukitFK3GYkQkDW1I=,tag:3iOiFAj5LJ9PHx3NXnxzMQ==,type:comment]
    tunnelId: ENC[AES256_GCM,data:mwpHpnKQRGTAeVdxd6pf3m1gwxIQFxXzxTm1J7YSNwveAEoZ,iv:INxIKhJ1OFPZbfN1ccVpejFK0xzrUs9vZ7WUWLJ6eck=,tag:SR9FjCYtRP+SwmUPF2SENQ==,type:str]
    #ENC[AES256_GCM,data:QUXXI11zBKGT9MwJo88g+NZa3Pg=,iv:o5Z6vbLsafSjkT29G7zEZT4h8SeRDNOaGWQ4wZpr1Q8=,tag:Q6WXoyaZchcLGNso0e+d5w==,type:comment]
    secret: ENC[AES256_GCM,data:RImpNmYFB/xBYYjLvbaSWAESX6jt1D9p9/g5rKsxbDxmPvl8OMLko9xSXVaamDUaCGVGwrair20S3dqlONNnldWJUw2CW1kLSRwHVYviPIgwjyFxSEGhRqBw804iEKj/94xSibwYUkeMnlAocvU1KOT/VT6Nk04iAuAsdSKq8HxsvZqLU774vnbw2xHpRHrdBhprkW5aPD2MvAsZH0w0rV6SsJuSMuqf8NTTMUwTSUQET4xmh0I/oQ==,iv:UMRW7xMLbivFhvv8xYD5gjmF8L14Q9yiLyPfE46ZQxI=,tag:QJzqwY6jv0pg4J4r3ZS+AQ==,type:str]
sops:
    age:
        - recipient: age17rl8aj6z7me9rj8vpjesujxpkwrducrhtdv7fvamm592z8280pusfrruup
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZmdYM3pJYlJ6cTlIUlV6
            QjRla2JBM0s4RkNxdHE3Nmhicys3aTIxV3o0CnRra0w2cnhGaXRHdGVSS3p6UTlo
            RkgrejIzVE9FUzk1OXViUmZzVGxuNTAKLS0tIGsvNVAxcnhlU2xScWRQNndpMFZN
            RHNxSjhPMTZ2NVo3TTdjNnVBWlpQZzQK3Z+QZMWbahb6nl1jBjIXxF/A9ptv9chz
            RwQHPegoUH+JF8klpYmKMjYzwFMl00nGP4ymBvEfC3slUG/dYTb/TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-29T13:09:59Z"
    mac: ENC[AES256_GCM,data:QIe77PEtT2/WXsv+s9vbbGXPEQZ0T6z5NONi1VZ06r3mngLaD+CRpUCIgay3UHdBkqhkTQkewQrWqNxznMiM+v84MCYh32e7kClg7USZol3qNuu6AaWra/SDrTz5cAvuvjmQK49/3o4w3VGopwAuHm1rI+s9vpi5N9KZHJvZgZ4=,iv:jsWms8pbI3QxuYN7WD6JJWPzkmKpl4qI4SToflmeud0=,tag:aopxWotsuWqwZRIzDDZdpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
